var searchIndex = [
  { title: "Home - Sichuan Yiyuan General Equipment", keywords: "home yiyuan natural gas compressor manufacturer products news about contact company introduction", url: "index.html" },
  { title: "About Us - Company Profile", keywords: "about company profile sichuan yiyuan general equipment introduction history", url: "about.html" },
  { title: "News - Company Updates", keywords: "news company updates industry information announcements latest", url: "news.html" },
  { title: "Products - Compressor Catalog", keywords: "products catalog compressor all models types", url: "products.html" },
  { title: "Certificates - Patents Licenses", keywords: "certificates patents business licenses qualifications awards", url: "certificates.html" },
  { title: "Message Board - Feedback", keywords: "message board contact surveys feedback customer", url: "message.html" },
  { title: "Contact Us - After-Sales Service", keywords: "contact us after-sales service training location address phone email", url: "contact.html" },
  { title: "Company News - Latest Updates", keywords: "company news latest updates announcements sichuan yiyuan", url: "p8.html" },
  { title: "Industry News - Compressor Industry", keywords: "industry news compressor market trends updates", url: "p9.html" },
  { title: "Downloads - Documentation", keywords: "downloads product documentation manuals brochures files", url: "p14.html" },
  { title: "Employee Life - Company Culture", keywords: "employee life company culture team activities staff", url: "p15.html" },
  { title: "Partners - Business Partners", keywords: "partners business cooperation clients customers", url: "p16.html" },
  { title: "Surveys - Customer Feedback", keywords: "surveys customer feedback questionnaire form", url: "p17.html" },
  { title: "After-Sales Service - Support", keywords: "after-sales service training support maintenance repair", url: "p18.html" },
  { title: "Franchise - Investment", keywords: "franchise investment opportunities business dealer distributor", url: "p19.html" },
  { title: "Careers - Job Opportunities", keywords: "careers job opportunities recruitment hiring employment", url: "p20.html" },
  { title: "Location - Company Address", keywords: "location company address map directions contact", url: "p21.html" },
  { title: "Legal Notice - Terms", keywords: "legal notice terms conditions privacy policy", url: "p22.html" },
  { title: "Site Map - Navigation", keywords: "site map website navigation all pages", url: "p23.html" },
  { title: "Pipeline Booster & Gas Lift Compressor", keywords: "pipeline booster gas lift compressor natural transmission", url: "p24.html" },
  { title: "CNG Compressor - Compressed Natural Gas", keywords: "CNG compressor compressed natural gas vehicle fuel station", url: "p25.html" },
  { title: "Natural Gas & Shale Gas Wellhead Compressor", keywords: "natural gas shale gas coal bed methane wellhead compressor extraction", url: "p26.html" },
  { title: "Molecular Sieve Gas Dehydrator", keywords: "molecular sieve gas dehydrator drying water removal", url: "p27.html" },
  { title: "Electrical Control Cabinet - PLC", keywords: "electrical control cabinet PLC VFD variable frequency panel", url: "p28.html" },
  { title: "Business Licenses - Certificates", keywords: "business licenses company certificates qualifications legal", url: "p30.html" },
  { title: "Product Features - Compressor Specifications", keywords: "product features reciprocating piston compressor specifications characteristics advantages", url: "p31.html" },
  { title: "Product Test Reports - Quality", keywords: "product test reports quality testing inspection certification", url: "p32.html" },
  { title: "User Reviews - Customer Feedback", keywords: "user reviews customer feedback testimonials ratings", url: "p33.html" },
  { title: "Environmental Compliance - Green", keywords: "environmental compliance green manufacturing eco-friendly emission", url: "p34.html" },
  { title: "Patents - Technology", keywords: "patents technology innovation intellectual property", url: "p35.html" },
  { title: "Reciprocating Piston Compressor Series", keywords: "reciprocating piston compressor series models types natural gas", url: "p36.html" },
  { title: "Hydrogen & Nitrogen Compressor", keywords: "hydrogen nitrogen compressor gas booster high pressure", url: "p37.html" },
  { title: "Chemical & Process Compressor", keywords: "chemical process compressor industrial gas petrochemical", url: "p38.html" },
  { title: "About Yiyuan - Company History", keywords: "about yiyuan company history sichuan general equipment profile", url: "p43.html" },
  { title: "Compressor Parts - Spare Parts", keywords: "compressor parts spare components accessories maintenance", url: "p48.html" }
];
